 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: pythonapp
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: pythonapp
   template:
     metadata:
       labels:
         app: pythonapp
     spec:
       containers:
       - name: pythonapp
         image: openwitclub/pythonapp:latest
         imagePullPolicy: IfNotPresent
         ports:
         - containerPort: 5055
