apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openwitclub/pythonapp
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: openwitclub/pythonapp
    spec:
      containers:
      - name: openwitclub/pythonapp
        image: openwitclub/pythonapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000